### ISSUE TITLE
noise value gives temperature values

### ISSUE THREAD

**Issue by lecabel** [marcoroth/netatmo-ruby#5]
Hi, 
when query for noise, it return the temperature.
irb(main):027:0> station_data.devices.first.noise
=> #<Netatmo::DashboardData::Temperature:0x00005646ba885048 @time=2020-09-03 18:44:58 +0200, @value=26.7, @min=23.7, @max=31.0, @min_date=2020-09-03 12:21:54 +0200, @max_date=2020-09-03 16:03:41 +0200, @trend=#<Netatmo::Util::TempTrend:0x00005646ba884f80 @value=0>, @unit="°C">
irb(main):028:0>

thanks!

**Comment by marcoroth** [comment]
Thanks @lecabel for reporting this bug! I've released `0.1.3` which should fix this issue.

Please reopen this issue if there is still something wrong! 😊
